package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import gui.detail.AnimalsTab;
import gui.detail.EmployeesTab;
import gui.detail.SpatialObjectsTab;
import gui.map.ZooMapPanel;
import javafx.scene.input.ZoomEvent;

import javax.swing.*;
import java.awt.*;

/**
 * Created by mlyko on 20.10.2015.
 */
public class ContentPanel extends JPanel {
	private JPanel rootPanel;
	public JPanel detailWrapper;
	public JPanel mapWrapper;

	public ZooMapPanel mapPanelContent;
	public SpatialObjectsTab spatialObjectsTab;
	public AnimalsTab animalsTab;
	public EmployeesTab employeesTab;

	public ContentPanel() {
		add(rootPanel);

		mapPanelContent = new ZooMapPanel(this);
		spatialObjectsTab = new SpatialObjectsTab(this);
		animalsTab = new AnimalsTab(this);
		employeesTab = new EmployeesTab(this);

		JTabbedPane detailTabsPane = new JTabbedPane();
		detailTabsPane.addTab("Objects", spatialObjectsTab);
		detailTabsPane.addTab("Animals", animalsTab);
		detailTabsPane.addTab("Employees", employeesTab);

		mapWrapper.add(mapPanelContent);
		detailWrapper.add(detailTabsPane);
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		rootPanel = new JPanel();
		rootPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		mapWrapper = new JPanel();
		mapWrapper.setLayout(new BorderLayout(0, 0));
		rootPanel.add(mapWrapper, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		detailWrapper = new JPanel();
		detailWrapper.setLayout(new BorderLayout(0, 0));
		rootPanel.add(detailWrapper, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(300, -1), null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootPanel;
	}
}
