package cz.vutbr.fit.pdb.ateam.gui.tabs.lists;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import cz.vutbr.fit.pdb.ateam.controller.Controller;
import cz.vutbr.fit.pdb.ateam.controller.AnimalsTabController;
import cz.vutbr.fit.pdb.ateam.gui.BasePanel;
import cz.vutbr.fit.pdb.ateam.utils.Utils;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 * @Author Tomas Hanus on 12/12/2015.
 */
public class AnimalsListPanel extends BasePanel {
	private JTable animalsTable;
	private AnimalsTabController controller;
	private JPanel rootPanel;
	private JButton addNewAnimalButton;
	private JPanel tablePanel;
	private JPanel datePickerBox;
	private JLabel datePickerLabel;
	private JRadioButton todayRadioButton;
	private JRadioButton historyRadioButton;
	private JDatePickerImpl datePicker;

	public AnimalsListPanel(AnimalsTabController controller) {
		this.controller = controller;
		$$$setupUI$$$();
		add(rootPanel);
		initUI();
	}

	private void initUI() {
		switchToToday();
		initializeDatePicker();

		initializeTodayHistoryRarioButtons();

		Utils.setComponentFixSize(addNewAnimalButton, 200, 25);
		addNewAnimalButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				controller.addNewAnimalAction();
			}
		});
	}

	private void initializeTodayHistoryRarioButtons() {
		todayRadioButton.setSelected(true);

		ButtonGroup bg = new ButtonGroup();
		bg.add(todayRadioButton);
		bg.add(historyRadioButton);

		todayRadioButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				controller.actualDateSwitchAction(true);
			}
		});

		historyRadioButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				controller.showHistorySwitchAction();
			}
		});

	}


	/**
	 * Method creates and initialize DatePicker to show today's date.
	 */
	private void initializeDatePicker() {
		final UtilDateModel dateModel = new UtilDateModel();
		final JDatePanelImpl datePanel = new JDatePanelImpl(dateModel);

		datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

		JFormattedTextField textField = datePicker.getJFormattedTextField();
		textField.setFont(new Font("Segoe UI Semilight", Font.BOLD, 14));
		dateModel.setValue(Calendar.getInstance().getTime());
		this.datePickerBox.removeAll();
		this.datePickerBox.add(datePicker);

		datePicker.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				controller.datePickerChangedAction(dateModel.getValue());
			}
		});
	}

	public void setAnimalsTable(JTable table) {
		animalsTable = table;
		tablePanel.removeAll();

		JScrollPane jScrollPane = new JScrollPane(animalsTable);
		tablePanel.add(jScrollPane, BorderLayout.NORTH);
	}

	@Override
	public Controller getController() {
		return this.controller;
	}

	/**
	 * Method switches DatePickerPanel to display Today and hides DatePicker
	 */
	public void switchToToday() {
		todayRadioButton.setSelected(true);
		datePickerBox.setVisible(false);
		datePickerLabel.setVisible(false);
	}


	/**
	 * Method displays datePicker to pick from past or today's date and initializes DatePicker.
	 */
	public void switchToPast() {
		datePickerBox.setVisible(true);
		datePickerLabel.setVisible(true);

		initializeDatePicker();
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		rootPanel = new JPanel();
		rootPanel.setLayout(new GridLayoutManager(8, 8, new Insets(0, 0, 0, 0), -1, -1));
		tablePanel = new JPanel();
		tablePanel.setLayout(new BorderLayout(0, 0));
		rootPanel.add(tablePanel, new GridConstraints(6, 0, 1, 8, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JLabel label1 = new JLabel();
		label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, 20));
		label1.setText("Animals List");
		rootPanel.add(label1, new GridConstraints(5, 0, 1, 7, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label2 = new JLabel();
		label2.setFont(new Font(label2.getFont().getName(), Font.BOLD, 20));
		label2.setText("Filter by date:");
		rootPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		rootPanel.add(spacer1, new GridConstraints(2, 5, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(25, -1), null, null, 0, false));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		rootPanel.add(panel1, new GridConstraints(3, 1, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		datePickerLabel = new JLabel();
		datePickerLabel.setFont(new Font(datePickerLabel.getFont().getName(), Font.BOLD, 18));
		datePickerLabel.setText("Pick:");
		panel1.add(datePickerLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		datePickerBox = new JPanel();
		datePickerBox.setLayout(new BorderLayout(0, 0));
		panel1.add(datePickerBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(150, -1), null, new Dimension(150, -1), 0, false));
		final Spacer spacer2 = new Spacer();
		rootPanel.add(spacer2, new GridConstraints(7, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		final JSeparator separator1 = new JSeparator();
		rootPanel.add(separator1, new GridConstraints(1, 0, 1, 8, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		final JSeparator separator2 = new JSeparator();
		rootPanel.add(separator2, new GridConstraints(4, 0, 1, 8, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		final JLabel label3 = new JLabel();
		label3.setFont(new Font(label3.getFont().getName(), Font.BOLD, 20));
		label3.setText("Create new Animal:");
		rootPanel.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		addNewAnimalButton = new JButton();
		addNewAnimalButton.setFont(new Font(addNewAnimalButton.getFont().getName(), Font.BOLD, addNewAnimalButton.getFont().getSize()));
		addNewAnimalButton.setText("Create");
		rootPanel.add(addNewAnimalButton, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, new Dimension(85, -1), 0, false));
		todayRadioButton = new JRadioButton();
		todayRadioButton.setText("Today");
		rootPanel.add(todayRadioButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		historyRadioButton = new JRadioButton();
		historyRadioButton.setText("History");
		rootPanel.add(historyRadioButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootPanel;
	}

	public class DateLabelFormatter extends JFormattedTextField.AbstractFormatter {

		private String datePattern = "  yyyy-MM-dd";
		private SimpleDateFormat dateFormatter = new SimpleDateFormat(datePattern);

		@Override
		public Object stringToValue(String text) throws ParseException {
			return dateFormatter.parseObject(text);
		}

		@Override
		public String valueToString(Object value) throws ParseException {
			if (value != null) {
				Calendar cal = (Calendar) value;
				return dateFormatter.format(cal.getTime());
			}

			return "";
		}
	}

}
